### ISSUE TITLE
如何规范window？

### ISSUE THREAD

**Issue by xubillde** [ginhoor/GHApplicationMediator#2]
尝试了更换[[UIApplication sharedApplication] delegate].window.rootViewController，没有反应

**Comment by ginhoor** [comment]
是的，[UIApplication sharedApplication].delegate.window默认是nil，你需要在某个模块中创建一个Window并赋值给[UIApplication sharedApplication].delegate.window。

**Comment by xubillde** [comment]
可以了，有个组件没加载，一个vc上用到了，结果就卡住了，没问题了

**Comment by xubillde** [comment]
3.0有计划吗？多个可能依赖

**Comment by xubillde** [comment]
实际使用过程中还是出现过由于依赖模块关系，导致初始化混乱的问题。这个后面咋解决的？暂时我这边还没碰到

**Comment by ginhoor** [comment]
嗯，暂时没有空做3.0。理论上是模块都是独立的业务，比如用户模块注册，通讯模块注册。如果你需要的是通讯模块必须在用户模块登录成功后才能注册，那你需要另一套通知机制来解决这种业务关系，这个框架目前只能解决静态注册模块化。

**Comment by xubillde** [comment]
👌，谢谢，明白了，load自动注册。有动态的，动态调用注册即可
